import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/ui/Navigation";

export const metadata = {
  title: "Summer Camp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#F9FAFB]">
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  );
}
